name: py310_new
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2022.12.7=ha878542_0
  - ld_impl_linux-64=2.40=h41732ed_0
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=12.2.0=h65d4601_19
  - libgomp=12.2.0=h65d4601_19
  - libnsl=2.0.0=h7f98852_0
  - libsqlite=3.40.0=h753d276_0
  - libuuid=2.38.1=h0b41bf4_0
  - libzlib=1.2.13=h166bdaf_4
  - ncurses=6.3=h27087fc_1
  - openssl=3.1.0=h0b41bf4_0
  - pip=23.0.1=pyhd8ed1ab_0
  - python=3.10.10=he550d4f_0_cpython
  - readline=8.2=h8228510_1
  - rpy2=3.5.8=py310r42h0a54255_0
  - setuptools=67.6.1=pyhd8ed1ab_0
  - tk=8.6.12=h27826a3_0
  - wheel=0.40.0=pyhd8ed1ab_0
  - xz=5.2.6=h166bdaf_0
  - pip:
      - anyio==3.6.2
      - argon2-cffi==21.3.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.2.3
      - astcheck==0.3.0
      - asttokens==2.2.1
      - attrs==22.2.0
      - backcall==0.2.0
      - beautifulsoup4==4.11.2
      - bleach==6.0.0
      - cffi==1.15.1
      - click==8.1.3
      - comm==0.1.2
      - contourpy==1.0.7
      - cycler==0.11.0
      - debugpy==1.6.6
      - decorator==5.1.1
      - defusedxml==0.7.1
      - entrypoints==0.4
      - executing==1.2.0
      - fastjsonschema==2.16.3
      - fonttools==4.39.0
      - fqdn==1.5.1
      - idna==3.4
      - ipykernel==6.21.3
      - ipython==8.11.0
      - ipython-genutils==0.2.0
      - ipywidgets==8.0.4
      - isoduration==20.11.0
      - jedi==0.18.2
      - jinja2==3.0.3
      - joblib==1.2.0
      - jsonpointer==2.3
      - jsonschema==4.17.3
      - jupyter-client==8.0.3
      - jupyter-contrib-core==0.4.2
      - jupyter-contrib-nbextensions==0.5.1
      - jupyter-core==5.2.0
      - jupyter-events==0.6.3
      - jupyter-highlight-selected-word==0.2.0
      - jupyter-latex-envs==1.4.6
      - jupyter-nbextensions-configurator==0.6.1
      - jupyter-server==1.13.5
      - jupyter-server-terminals==0.4.4
      - jupyterlab-pygments==0.2.2
      - jupyterlab-widgets==3.0.5
      - kiwisolver==1.4.4
      - lxml==4.9.2
      - markupsafe==2.1.2
      - mathjax==0.1.2
      - matplotlib==3.7.1
      - matplotlib-inline==0.1.6
      - mistune==0.8.4
      - nbclassic==0.5.3
      - nbclient==0.7.2
      - nbconvert==5.6.1
      - nbformat==5.7.3
      - nbparameterise==0.6
      - nest-asyncio==1.5.6
      - notebook==6.5.3
      - notebook-shim==0.2.2
      - numpy==1.24.2
      - packaging==23.0
      - pandas==1.5.3
      - pandocfilters==1.5.0
      - parso==0.8.3
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - pillow==9.4.0
      - platformdirs==3.1.1
      - plotly==5.13.1
      - prometheus-client==0.16.0
      - prompt-toolkit==3.0.38
      - psutil==5.9.4
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pycparser==2.21
      - pygments==2.14.0
      - pyparsing==3.0.9
      - pyrsistent==0.19.3
      - python-dateutil==2.8.2
      - python-json-logger==2.0.7
      - pytz==2022.7.1
      - pytz-deprecation-shim==0.1.0.post0
      - pyyaml==6.0
      - pyzmq==25.0.1
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - scikit-learn==1.2.2
      - scipy==1.10.1
      - seaborn==0.12.2
      - send2trash==1.8.0
      - six==1.16.0
      - sniffio==1.3.0
      - soupsieve==2.4
      - stack-data==0.6.2
      - tenacity==8.2.2
      - terminado==0.17.1
      - testpath==0.6.0
      - threadpoolctl==3.1.0
      - tinycss2==1.2.1
      - tornado==6.2
      - traitlets==5.9.0
      - tzdata==2022.7
      - tzlocal==4.2
      - uri-template==1.2.0
      - wcwidth==0.2.6
      - webcolors==1.12
      - webencodings==0.5.1
      - websocket-client==1.5.1
      - widgetsnbextension==4.0.5
prefix: /opt/conda/envs/py310_new
